name: Release Script Jar

on:
  push:
    tags:
      - "script-*/[0-9]*.[0-9]*.[0-9]*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Extract module and version from tag
        id: extract
        run: |
          TAG=$(echo $GITHUB_REF_NAME)
          MODULE=$(echo $TAG | cut -d'/' -f1)
          VERSION=$(echo $TAG | cut -d'/' -f2)
          echo "MODULE=$MODULE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version_code in manifest
        run: |
          VERSION_CODE=$(echo $VERSION | awk -F. '{print $1 * 100 + $2 * 10 + $3}')
          MANIFEST_PATH=$MODULE/src/main/resources/manifest.json
          jq --argjson version_code "$VERSION_CODE" '.version_code = $version_code' $MANIFEST_PATH > tmp_manifest.json
          mv tmp_manifest.json $MANIFEST_PATH

      - name: Build jar
        run: |
          ./gradlew :$MODULE:clean :$MODULE:scriptJar

      - name: Publish jar and mapping
        run: |
          mkdir -p release-artifacts
          cp -r $MODULE/build/obfuscated/* release-artifacts/

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MODULE }}-artifacts
          path: release-artifacts/
